#language: es
# Author : Ismael Carvajal

Característica: Registrar una oferta
  Como Buyer
  Quiero crear una oferta
  Para que el traider pueda verla

  Esquema del escenario: Crear una oferta
    Dado que el {actor} ingresa a la aplicacion
    Cuando el {actor} ingresa una '<ofert>' sin estandarizar en el offer input y llena los campos de '<protein>','<supplier>','<temperature>','<inconterm>','<qty>','<location>','<date>','<comment>'
    Entonces el {actor} recibe su mensaje de confirmacion 'Offer list'
    Ejemplos:
      | ofert                                                                                                                                                                                                      | protein | supplier            | temperature | inconterm          | qty   | location         | date       | comment             |
      | OLYMEL-PORK FCA Montreal, QC FCA Red Deer, AB Good afternoon, We can offer the following for Mexico market for END March loading QUEBEC Code Produits PRICE: 033111C BONELESS HAM NATURAL FAT COVER 1.25 $ | Pork    | Olymel S.E. C./L.P. | Fresh       | FCA - Free Carrier | 40000 | Hatfield, PA, US | 30/04/2024 | Test-Automatizacion |
      #| NO DOCS Hat = FOB Hatfield PA Col = FOB Coldwater Mi FACS = FOB Frozen assets Chicago Cold Link – FOB Holland MI Artico – FOB Chicago UP - Universal Pure is in Malvern, PA Fresh: FOB Sku Description Plant Ship Date & Quantity Price 4951 Bnls Loin Strap Off, FTR extra trim COL 44cs 1.80 1081 Tenders COL 1000cs, 4/19 1.80 1178 Bnls Sirloins COL 1ld, 4/24; 1ld, 4/26; 1.35 1504 Bnls Sirloins, Combo COL 1ld, 4/24; 1ld, 4/26; 1.27 1055 Bone In Pics COL 400cs, prompt; 500cs, 4/20; 1ld, 4/23; 1ld 4/24; 1ld, 4/25 0.92 1400 Bone In Pic Combos COL 1ld, 4/23; 1ld 4/24; 1ld, 4/25 0.85 1469 Ham Hock Combo COL 1ld, 4/17 0.50 2235 Bacon Ends and Pieces Combo HAT 1ld, 4/25 0.50 1055 Bone In Pics HAT 500cs, prompt 0.92 1056 Bnls Loins Strap On HAT 1ld, 4/18; 1ld, 4/22 | Pork    | Clemens Food Group, LLC            | Fresh       | FCA - Free Carrier | 40000 | Chicago, IL, US | 04/26/2024 | 40000   |
      #| OLYMEL-PORK FCA Montreal, QC FCA Red Deer, AB Good afternoon, We can offer the following for Mexico market for END March loading  RED DEERCode Description PRICE: 0701C SKIMPY BELLIES 1.31 $ 1322C MAIN MUSCLE COV 1.90 $ 250111C BONELESS PICNIC 20kgs 1.28 $ 2501C BONELESS PICNIC 1.25 $                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | Pork    | Olymel S.E. C./L.P.                | Fresh       | FCA - Free Carrier | 40000 |                 |            |         |
      #| SMITHFIELD Fresh Bi Loin COV @ $1.12 / lb FOB Denison, IA (no docs) to ship on 3/7 Fresh Bnls Loin COV @ $1.45/ lb FOB Milan, MO (no docs) to ship on 3/8 Fresh Backribs COV  @                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | Pork    | Smithfield Fresh Meats Sales Corp. | Fresh       | FCA - Free Carrier | 40000 |                 |            |         |
      #| Smithfield FRESH Product Price Update (no docs) 4/16/2024: Fresh Bi Loin COV @$1.29/lb EXW Sioux Falls, SD to ship on 4/20 Fresh Bnls Loin COV @$1.64/lb EXW Denison, IA to ship on 4/18 Fresh Bnls Sirloin COV @$1.36/lb EXW Milan, MO to ship on 4/20 Fresh Bi Butt COV @$1.59/lb EXW Denison, IA to ship on 4/17                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Pork    | Smithfield Fresh Meats Sales Corp. | Fresh       | FCA - Free Carrier | 40000 |                 |            |         |
      #| smithfield hams - 2 cargas manana de Tarheel - saliendo en formula, pero Podemos pasar bid en precio fijo - no docs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | Pork    | Smithfield Fresh Meats Sales Corp. | Fresh       | FCA - Free Carrier | 40000 |                 |            |         |
      #| SEABOARD FOODS EXPORT OFFERING FOB Delivered Laredo (Entregado Laredo) Fresh in combos Belly skin Cuero de panza fresh en combos Del Laredo 2/12 Entregado día-12 $.30 $.40 Frozen Salivary glands Glandula Congelado 2 weeks 2 semanas $.48 $.58                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Pork    | Seaboard Foods                     | Fresh       | FCA - Free Carrier | 40000 |                 |            |         |



  Esquema del escenario: Editar
    Cuando el {actor} quiere editar una oferta
    Cuando el {actor} modifica los campos de '<protein>','<supplier>','<temperature>','<inconterm>','<qty>','<location>','<date>','<comment>' en la edicion de la estandarizacion
    Entonces el {actor} puede publicar las ofertas estandarizadas y ver 'Offer list'
    Ejemplos:
      | protein | supplier                | temperature | inconterm          | qty   | location | date | comment |
      | Pork    | Clemens Food Group, LLC | Fresh       | FCA - Free Carrier | 40000 |          |      |         |

